### ISSUE TITLE
empty homepage on 7.8.4

### ISSUE THREAD

**Issue by corradocampisano** [Bonitasoft-Community/Build-Bonita#15]
![Screenshot from 2019-06-14 17-36-44](https://user-images.githubusercontent.com/25619972/59520863-31694a80-8ecb-11e9-82b9-eae2feb45f24.png)

**Comment by amottier** [comment]
Do you get this issue only on the version of Bonita Studio you build yourself or does it also apply to an Studio runtime provided by Bonitasoft?

If it apply to both I recommend to follow the guidelines available at the bottom of this documentation page (I'm assuming you are using Linux): https://documentation.bonitasoft.com/bonita/7.8/bonita-bpm-studio-installation#toc12

**Comment by corradocampisano** [comment]
Hi, I donwloaded the "[Bonita Studio zip package ](https://www.bonitasoft.com/products/download/bonita-all-one-7-8-4)" version from here:
https://www.bonitasoft.com/downloads?version=7.8.4&os=linux

Anyway, installing libwebkitgtk solved the problem, thx.

![Uploading Screenshot from 2019-06-17 09-46-44.png…]()
