### ISSUE TITLE
Unable to build Bonita 7.9.2

### ISSUE THREAD

**Issue by tbouffard** [Bonitasoft-Community/Build-Bonita#16]
Various issues with current `master` branch (see e7372f12a37ed698381cf992123d70ef9f5cc212)
- engine still builds with maven instead of gradle
- connectors
  - some tags are wrong
  - some connectors depends on `bonita-engine:7.9.0-SNAPSHOT`
  - connector-database depends on the oracle jdbc driver which is not available in public repository
- web-pages: depends on the `com.bonitasoft.deployer.bonita-resources-deployer: 0.1.25` plugin which is not available publicly
- studio
  - required a toolchains.xm file for JDK11
  - p2 repository is still 7.7 instead of 4.10

**Comment by tbouffard** [comment]
I have started working on this subject in https://github.com/tbouffard/Build-Bonita/pull/1
I have enabled Travis CI builds to demonstrate the issue

**Comment by tbouffard** [comment]
The issue about connectors will be fixed in bonita-studio 7.9.3, see https://github.com/bonitasoft/bonita-studio/commit/c81472042cead756bd1d777e8aff6b22728d5ad4

**Comment by amottier** [comment]
@tbouffard in our internal issue tracker I report the issue BR-168 that prevent build of Bonita 7.9 with the community script.

I have a bunch of changes on this build script locally waiting for the issue to be solved.

**Comment by tbouffard** [comment]
Hm, the issue you mention is about `Building Bonita Engine does not publish org.bonitasoft.engine.test:bonita-server-test-utils:jar to local Maven repository leading to missing dependency when trying to build bonita-userfilter-tests.`

We have never run the tests in the past and the PR I am working on shows that Travis CI has no issue when building bonita-userfilters without tests

```
Processing bonita-userfilters 7.9.2
============================================================
Cloning into 'bonita-userfilters'...
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 22421 (delta 96), reused 119 (delta 27), pack-reused 22224
Receiving objects: 100% (22421/22421), 2.11 MiB | 13.15 MiB/s, done.
Resolving deltas: 100% (11121/11121), done.
HEAD is now at 46f9f866 [USER-FILTERS RELEASE] Prepare release 7.9.2
skip clean
============================================================
```

**Comment by tbouffard** [comment]
@amottier can you also make your working branch public please?
Otherwise I cannot see what you are working on; I don't want to work on something you are already working on 😄

**Comment by amottier** [comment]
@tbouffard I published my branch 7.9-build-attempt.

I don't run the test in my script (at least not unit tests) but it seems that bonita-server-test-utils is still required (I guess for an integration test) or maybe because some inconsistency in our dependencies.

**Comment by tbouffard** [comment]
@amottier the current difference between your branch and mine is that you try to build 7.9.1 whereas I am on 7.9.2

**Comment by amottier** [comment]
#17 should fix the issue. At least I managed to successfully build 7.9.2 on my side with a clean Maven and Gradle cache and no connection to Bonitasoft internal repository.
@tbouffard can you review and test #17 ?

**Comment by amottier** [comment]
Fix in tag 7.9.2.

**Comment by tbouffard** [comment]
Something may missing in the README about the Studio maven settings mirrror requirements as described in https://github.com/bonitasoft/bonita-studio/commit/e5380870cd9ccdc5167d2de5c6191b786215a7d3

**Comment by amottier** [comment]
I currently prefer to keep the workaround in the script. I'm waiting for a final decision about if our internal Bonitasoft repository should be a mirror of the publicly available one or the opposite. If the public repository becomes the one used by default no need to update the readme.
