### ISSUE TITLE
build fails on bonita-ui-designer

### ISSUE THREAD

**Issue by gabrielsallum** [Bonitasoft-Community/Build-Bonita#2]
Hello,

The build script ceases on bonita-ui-designer. 
it seems that on some npm dependency : 

....
[INFO] [16:33:42] Finished 'bundle:html' after 6.11 s                                          [68/40449]
[INFO] [16:33:42] Starting 'pot'...
[INFO] [16:33:42] Starting 'bundle:js'...
[ERROR] /home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/frontend/node_modul
es/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
[ERROR] (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeo
f Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnPro
perty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRON
MENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB;var ENVIRONMENT_
IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS
_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(
x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){proces
s["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function 
read
[ERROR] 
[ERROR] Error: Failed to call done in a stream handler before 30000ms timeout.
[ERROR]     at null._onTimeout (/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-desi
gner/frontend/node_modules/gulp-jshint/src/stream.js:32:27)
[ERROR]     at Timer.listOnTimeout (timers.js:92:15)
[ERROR] 
[ERROR] npm ERR! Linux 4.4.8-300.fc23.x86_64
[ERROR] npm ERR! argv "/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/node
/node" "/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/node/node_modules/n
pm/bin/npm-cli.js" "run" "build"
[ERROR] npm ERR! node v4.4.7
[ERROR] npm ERR! npm  v2.15.8
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! page-builder@0.0.1 build: `gulp --dist`
[ERROR] npm ERR! Exit status 7
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the page-builder@0.0.1 build script 'gulp --dist'.
[ERROR] npm ERR! This is most likely a problem with the page-builder package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     gulp --dist
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs page-builder
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR! 
[ERROR] npm ERR!     npm owner ls page-builder
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/fronte
nd/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ui-designer ........................................ SUCCESS [  0.340 s]
[INFO] ui-designer-frontend ............................... FAILURE [06:37 min]
[INFO] ui-designer-backend ................................ SKIPPED
[INFO] ui-designer-backend-contract ....................... SKIPPED
[INFO] ui-designer-backend-webapp ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:37 min
[INFO] Finished at: 2017-01-28T16:34:43-05:00
[INFO] Final Memory: 15M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm build) on project u
i-designer-frontend: Failed to run task: 'npm run build' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui-designer-frontend

Upon further reading the npm log :
(Build-Bonita-BPM/bonita-ui-designer/backend/webapp/npm-debug.log)
....
204708 silly gunzTarPerm modified mode [ '_baseExtremum.js', 420, 436 ]
204709 silly gunzTarPerm extractEntry templateSettings.js
204710 silly gunzTarPerm modified mode [ 'templateSettings.js', 420, 436 ]
204711 silly gunzTarPerm extractEntry _baseFilter.js
204712 silly gunzTarPerm modified mode [ '_baseFilter.js', 420, 436 ]
204713 silly gunzTarPerm extractEntry templateSettings.js
204714 silly gunzTarPerm modified mode [ 'templateSettings.js', 420, 436 ]
204715 silly gunzTarPerm extractEntry _baseFilter.js
204716 silly gunzTarPerm modified mode [ '_baseFilter.js', 420, 436 ]
204717 error error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/backend/webapp/node_modules/karma-babel-preprocessor/node_modules/babel-core/node_modules/babel-register/node_modules/core-js/fn/string'
204717 error error rolling back     at Error (native)
204717 error error rolling back  { [Error: ENOTEMPTY: directory not empty, rmdir '/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/backend/webapp/node_modules/karma-babel-preprocessor/node_modules/babel-core/node_modules/babel-register/node_modules/core-js/fn/string']
204717 error error rolling back   errno: -39,
204717 error error rolling back   code: 'ENOTEMPTY',
204717 error error rolling back   syscall: 'rmdir',
204717 error error rolling back   path: '/home/gab/prj/bonita_tomcat/bonita_source/Build-Bonita-BPM/bonita-ui-designer/backend/webapp/node_modules/karma-babel-preprocessor/node_modules/babel-core/node_modules/babel-register/node_modules/core-js/fn/string' }

trying to rmdir on a non empty dir...

**Comment by amottier** [comment]
I just test the script recently and the build of the UI Designer run without any problem. Can you give a try to the latest version and create a new issue if you still have trouble building the UI Designer? Thanks.
