### ISSUE TITLE
[feature] allow to build the dev branch

### ISSUE THREAD

**Issue by tbouffard** [Bonitasoft-Community/Build-Bonita#41]
The current solution only allows to build a tagged version of Bonita.
People who want to make contributions need to base their work on a branch, generally `master` or `dev`.
They need to be able to build Bonita components the targeted project requires so letting them build the whole Bonita solution will help doing that.

In addition, letting build a dedicated branch could also ensure that the master and dev branch are buildable. We could setup a [Travis CI cron](https://docs.travis-ci.com/user/cron-jobs/) and [GitHub actions schedule](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule) to verify it

**Comment by rbioteau** [comment]
`master` doesn't exists anymore on public repositories.
