### ISSUE TITLE
Investigate Travis CI status not set on PR and branches

### ISSUE THREAD

**Issue by tbouffard** [Bonitasoft-Community/Build-Bonita#47]
Seen in #46 and #48
The Travis CI build is run (https://travis-ci.org/Bonitasoft-Community/Build-Bonita/builds/649894121) but no status are shown on the PR and commit

![image](https://user-images.githubusercontent.com/27200110/74521107-2dd60980-4f19-11ea-9b51-6d4ab5c0d147.png)

**Comment by tbouffard** [comment]
Latest commit status by Travis CI on master branch: 887746b678fad1a8ccb3d6ebfa256a5ab05a0215 (Dec 9, 2019)

![image](https://user-images.githubusercontent.com/27200110/76209697-ca32b980-6202-11ea-9bc9-37333d0e0789.png)

**Comment by tbouffard** [comment]
It seems that Travis CI are now available, see #48 commit 8cab87f on 2020-03-28
The previous one (4b8639e on 2020-03-24) didn't show Travis status

![image](https://user-images.githubusercontent.com/27200110/77936336-0cf02a80-72b3-11ea-8140-fca90d812830.png)

@amottier did you change something in the Travis configuration?

**Comment by amottier** [comment]
@tbouffard I didn't touch the Travis configuration, I don't have any clues about what can be going on there.

**Comment by tbouffard** [comment]
Ok, thanks for the feedback
I am closing the issue as everything seems working now and eventually, we will reopen it if the issue occurs again
