### ISSUE TITLE
Remove jboss mirroring config from the GH workflow maven settings

### ISSUE THREAD

**Issue by tbouffard** [Bonitasoft-Community/Build-Bonita#61]
This has been introduced in #60 
Try to remove the need of the jboss repository in bonita-distrib and in all bonita repositories, then, remove the configuration here

**Comment by tbouffard** [comment]
Still used by distrib 7.12.1 (Bonita 2021.1)

https://github.com/bonitasoft/bonita-distrib/blob/7.12.1/pom.xml#L61-L68

**Comment by tbouffard** [comment]
Still used by dstrib 7.13.0 (Bonita 2021.2) 😒, see https://github.com/bonitasoft/bonita-distrib/blob/7.13.0/pom.xml#L71-L84

**Comment by rbioteau** [comment]
Looks like there will be a reference to restlet repository in 7.14

```
 <repository>
            <id>restlet.com</id>
            <name>restlet.com</name>
            <url>https://maven.restlet.talend.com</url>
  </repository>
```
