### ISSUE TITLE
build fail using a non public p2 repository

### ISSUE THREAD

**Issue by Nicodonald** [Bonitasoft-Community/Build-Bonita#8]
The build fail at bonita-studio :
`[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.bonitasoft.studio.patched-plugins:org.eclipse.emf.edapt.migration:1.2.2.201705070604 @ /opt/Bonita/Build-Bonita/bonita-studio/patched-plugins/org.eclipse.emf.edapt.migration/pom.xml
[INFO] Adding repository http://repositories.rd.lan/p2/7.7
[ERROR] Failed to resolve target definition /opt/Bonita/Build-Bonita/bonita-studio/platform/platform.target: Failed to load p2 metadata repository from location http://repositories.rd.lan/p2/7.7: Unknown Host: http://repositories.rd.lan/p2/7.7/content.xml: Unknown host repositories.rd.lan -> [Help 1]
`

**Comment by amottier** [comment]
I just update the build script for version 7.7.2, 7.7.3 and 7.7.5. They all use the public repository instead of the internal repository. Can you test this new version and let me know if it solves the issue?

**Comment by sparse91** [comment]
I have same issue with latest version.

**Comment by amottier** [comment]
Can you try the latest release https://github.com/Bonitasoft-Community/Build-Bonita/tree/7.8.0 ?

**Comment by sparse91** [comment]
Thank you. The problem solved but now I get another error:
```
[INFO] ui-designer-backend ................................ SUCCESS [  0.641 s]
[INFO] ui-designer-backend-contract ....................... SUCCESS [  0.303 s]
[INFO] ui-designer-backend-webapp ......................... SUCCESS [ 13.506 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.571 s
[INFO] Finished at: 2019-01-12T08:05:30+03:30
[INFO] ------------------------------------------------------------------------
Cloning into 'bonita-web-pages'...
warning: Could not find remote branch tags/7.8.0 to clone.
fatal: Remote branch tags/7.8.0 not found in upstream origin
```

**Comment by amottier** [comment]
Sorry I run successfully on my side due to a previous clone of the repository.
I fixed the script and published a new release. Can you test the latest one?
Thanks.

**Comment by amottier** [comment]
Successfully build also on 7.8.2. Closing this issue. Please open a new issue if you still have difficulties building Bonita Community Edition from sources.
